# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import algorithms.strings as module_0


def test_case_0():
    bytes_0 = b"z<\xa7\xb6[~\xb8G\x85U\xbc\x9e]]c\x9a\x80\xd7S"
    var_0 = module_0.count_binary_substring(bytes_0)
    assert var_0 == 17
