# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.strings as module_0


def test_case_0():
    str_0 = "q\"l HI'SgCp}Q\"'w=}L"
    var_0 = module_0.domain_name_1(str_0)
    assert var_0 == "q\"l HI'SgCp}Q\"'w=}L"
    var_1 = module_0.domain_name_1(var_0)
    var_2 = module_0.domain_name_2(var_1)
    assert var_2 == "q\"l HI'SgCp}Q\"'w=}L"
    var_3 = module_0.domain_name_2(var_1)
    var_4 = module_0.domain_name_2(var_3)
    var_5 = module_0.domain_name_1(var_4)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.domain_name_1(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = -781
    module_0.domain_name_2(int_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = 'jC_>9Sf"Jena\tv|\x0c4h'
    var_0 = module_0.domain_name_2(str_0)
    assert var_0 == 'jC_>9Sf"Jena\tv|\x0c4h'
    var_1 = module_0.domain_name_2(str_0)
    var_2 = module_0.domain_name_1(var_1)
    assert var_2 == 'jC_>9Sf"Jena\tv|\x0c4h'
    bool_0 = False
    str_1 = ".Jyb1:#0.V=Cw2\rl5"
    var_3 = module_0.domain_name_1(str_1)
    assert var_3 == "Jyb1:#0"
    var_4 = module_0.domain_name_1(var_0)
    module_0.domain_name_1(bool_0)
