# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.arrays as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\xde\x8b\xec\xa8,\xb6\xe7\xb8\x9e\xe6"
    var_0 = module_0.remove_duplicates(bytes_0)
    none_type_0 = None
    module_0.remove_duplicates(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = True
    module_0.remove_duplicates(bool_0)


def test_case_2():
    set_0 = set()
    tuple_0 = (set_0, set_0)
    var_0 = module_0.remove_duplicates(tuple_0)
