# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.arrays as module_0


def test_case_0():
    set_0 = set()
    none_type_0 = None
    var_0 = module_0.limit(set_0, max_lim=none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    dict_0 = {}
    var_0 = module_0.limit(dict_0, dict_0, dict_0)
    bytes_0 = b"\x05\xe8H\xa0k\xaa\xfci\x99.\x1de\x92P\x03\xa9\x85h\x04"
    var_1 = module_0.limit(var_0, bytes_0)
    var_2 = module_0.limit(bytes_0)
    none_type_0 = None
    var_3 = module_0.limit(bytes_0)
    module_0.limit(none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = ": !{?X4DeOSw\x0ci"
    var_0 = module_0.limit(str_0)
    var_1 = module_0.limit(str_0)
    str_1 = "93.E'nsM#K"
    var_2 = module_0.limit(str_1)
    none_type_0 = None
    tuple_0 = (var_2,)
    var_3 = module_0.limit(tuple_0, none_type_0)
    var_4 = module_0.limit(str_1)
    var_5 = module_0.limit(var_4, str_1, str_1)
    var_6 = module_0.limit(var_2)
    var_7 = module_0.limit(str_1, none_type_0)
    module_0.limit(none_type_0, max_lim=none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    int_0 = 1445
    module_0.limit(int_0)
