# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.strings as module_0


def test_case_0():
    bytes_0 = b"mq\xed"
    list_0 = [bytes_0, bytes_0]
    var_0 = module_0.count_binary_substring(list_0)
    assert var_0 == 0


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    module_0.count_binary_substring(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "\n         expands size of the array.\n         Time Complexity: O(n)\n        "
    var_0 = module_0.count_binary_substring(str_0)
    assert var_0 == 51
    float_0 = 2763.5
    module_0.count_binary_substring(float_0)
