# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.stack as module_0
import builtins as module_1


def test_case_0():
    bytes_0 = b"\x94\xdck\x11"
    list_0 = [bytes_0, bytes_0]
    var_0 = module_0.remove_min(list_0)
    var_1 = module_0.remove_min(list_0)


def test_case_1():
    bytes_0 = b"\x94\xdck\x11"
    list_0 = [bytes_0, bytes_0]
    var_0 = module_0.remove_min(list_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    float_0 = -474.61617
    module_0.remove_min(float_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = False
    int_0 = 201
    list_0 = [bool_0, bool_0, int_0, bool_0]
    var_0 = module_0.remove_min(list_0)
    list_1 = []
    object_0 = module_1.object(*list_1)
    var_1 = module_0.remove_min(list_1)
    module_0.remove_min(object_0)
