# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.arrays as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    list_0 = []
    var_0 = module_0.limit(list_0)
    object_0 = module_1.object(*list_0)
    module_0.limit(object_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b"\x99z\xb3\xcb\xfa\xba\x12\xa8\xbe"
    list_0 = [bytes_0]
    var_0 = module_0.limit(list_0)
    var_1 = module_0.limit(var_0)
    module_0.limit(bytes_0, max_lim=bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = 1528452
    module_0.limit(int_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bytes_0 = b"\x99z\xb3\xcb\xfa\xba\x12\xa8\xbe"
    list_0 = [bytes_0]
    var_0 = module_0.limit(list_0)
    module_0.limit(list_0, list_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = "~[sw3p1;ZxLR"
    str_1 = ","
    var_0 = module_0.limit(str_0, str_0)
    var_1 = module_0.limit(var_0)
    var_2 = module_0.limit(str_1)
    set_0 = {str_1, str_1}
    tuple_0 = (set_0, set_0, set_0, set_0)
    var_3 = module_0.limit(tuple_0)
    var_4 = module_0.limit(tuple_0, max_lim=set_0)
    module_0.limit(var_3, var_2)
