# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.strings as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = '"\nCreate a function that will validate if given parameters are valid geographical coordinates.\nValid coordinates look like the following: "23.32353342, -32.543534534". The return value should be either true or false.\nLatitude (which is first float) can be between 0 and 90, positive or negative. Longitude (which is second float) can be between 0 and 180, positive or negative.\nCoordinates can only contain digits, or one of the following symbols (including space after comma) -, .\nThere should be no space between the minus "-" sign and the digit after it.\n\nHere are some valid coordinates:\n-23, 25\n43.91343345, 143\n4, -3\n\nAnd some invalid ones:\n23.234, - 23.4234\nN23.43345, E32.6457\n6.325624, 43.34345.345\n0, 1,2\n\n'
    var_0 = module_0.domain_name_1(str_0)
    assert var_0 == '\nValid coordinates look like the following: "23'
    none_type_0 = None
    module_0.domain_name_1(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "Stack is empty"
    var_0 = module_0.domain_name_2(str_0)
    assert var_0 == "Stack is empty"
    var_1 = module_0.domain_name_1(var_0)
    assert var_1 == "Stack is empty"
    bytes_0 = b"8\xc9/="
    module_0.domain_name_1(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    float_0 = 3798.0
    module_0.domain_name_2(float_0)
