# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.dp as module_0


def test_case_0():
    str_0 = "`l:~N<p4gh)EpRHN"
    var_0 = module_0.longest_increasing_subsequence(str_0)
    assert var_0 == 5


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b"\x1f\x8c\xf7\x0c\x12;\x18\x8f"
    module_0.longest_increasing_subsequence_optimized(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b" \xa3"
    module_0.longest_increasing_subsequence_optimized2(bytes_0)


def test_case_3():
    list_0 = []
    var_0 = module_0.longest_increasing_subsequence_optimized2(list_0)
    assert var_0 == 0


def test_case_4():
    bytes_0 = b"\xa3"
    var_0 = module_0.longest_increasing_subsequence_optimized2(bytes_0)
    assert var_0 == 1


@pytest.mark.xfail(strict=True)
def test_case_5():
    str_0 = "`l:~N<pA4gh)EpRHN"
    module_0.longest_increasing_subsequence_optimized2(str_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    none_type_0 = None
    module_0.longest_increasing_subsequence_optimized(none_type_0)
