# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.backtrack as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = 8
    var_0 = module_0.palindromic_substrings_iter(int_0)
    module_0.palindromic_substrings(var_0)


def test_case_1():
    none_type_0 = None
    var_0 = module_0.palindromic_substrings(none_type_0)
    var_1 = module_0.palindromic_substrings(none_type_0)


def test_case_2():
    none_type_0 = None
    var_0 = module_0.palindromic_substrings_iter(none_type_0)


def test_case_3():
    none_type_0 = None
    var_0 = module_0.palindromic_substrings_iter(none_type_0)
    str_0 = "5)N_O{=r\r/]&/\x0c|4;"
    var_1 = module_0.palindromic_substrings(str_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = "h\\?j"
    int_0 = 5
    var_0 = module_0.palindromic_substrings_iter(int_0)
    var_1 = module_0.palindromic_substrings_iter(str_0)
    module_1.object(*var_1)
