# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.sort as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "!i<  nqST-:eb iU@"
    module_0.insertion_sort(str_0)


def test_case_1():
    bool_0 = True
    list_0 = [bool_0, bool_0]
    var_0 = module_0.insertion_sort(list_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = 556
    module_0.insertion_sort(int_0, int_0)


def test_case_3():
    bool_0 = True
    list_0 = [bool_0, bool_0]
    var_0 = module_0.insertion_sort(list_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    bool_0 = True
    list_0 = [bool_0, bool_0]
    bool_1 = False
    list_1 = [bool_0, bool_1, list_0]
    module_0.insertion_sort(list_1)


@pytest.mark.xfail(strict=True)
def test_case_5():
    bool_0 = True
    list_0 = [bool_0, bool_0]
    bool_1 = False
    list_1 = [bool_1, bool_0, bool_1, list_0]
    module_0.insertion_sort(list_1, list_1)


@pytest.mark.xfail(strict=True)
def test_case_6():
    bool_0 = True
    bool_1 = False
    list_0 = [bool_0, bool_1, bool_0, bool_1, bool_1]
    var_0 = module_0.insertion_sort(list_0)
    none_type_0 = None
    module_0.insertion_sort(none_type_0)
