# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.strings as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "'_7V"
    var_0 = module_0.first_unique_char(str_0)
    assert var_0 == 0
    set_0 = {str_0, str_0, str_0}
    var_1 = module_0.first_unique_char(set_0)
    assert var_1 == 0
    str_1 = "vg(d}`_kR@cr(/0"
    var_2 = module_0.first_unique_char(str_1)
    assert var_2 == 0
    var_3 = module_0.first_unique_char(set_0)
    assert var_3 == 0
    bool_0 = False
    module_0.first_unique_char(bool_0)


def test_case_1():
    str_0 = "\r#TZom\x0b%k>!fJd.*&!d"
    var_0 = module_0.first_unique_char(str_0)
    assert var_0 == 0


@pytest.mark.xfail(strict=True)
def test_case_2():
    complex_0 = 2682.509 - 336.6653j
    module_0.first_unique_char(complex_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    dict_0 = {}
    var_0 = module_0.first_unique_char(dict_0)
    assert var_0 == -1
    var_1 = module_0.first_unique_char(dict_0)
    assert var_1 == -1
    object_0 = module_0.first_unique_char(dict_0)
    assert object_0 == -1
    module_0.first_unique_char(object_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    bytes_0 = b"z\x84i0T\xcal\xdd%\xa5cY\xbe\x8dz\xf0\xf6\xc7"
    var_0 = module_0.first_unique_char(bytes_0)
    assert var_0 == 1
    module_0.first_unique_char(var_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    float_0 = -1449.300144
    list_0 = [float_0, float_0, float_0]
    var_0 = module_0.first_unique_char(list_0)
    assert var_0 == -1
    module_0.first_unique_char(var_0)
