# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import algorithms.arrays as module_0


def test_case_0():
    complex_0 = 2067 - 90.32907j
    list_0 = [complex_0]
    list_1 = [list_0, complex_0, list_0, complex_0]
    var_0 = module_0.remove_duplicates(list_1)


def test_case_1():
    set_0 = set()
    var_0 = module_0.remove_duplicates(set_0)
    var_1 = module_0.remove_duplicates(set_0)
