# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.backtrack as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    float_0 = 3.0
    module_0.palindromic_substrings(float_0)


def test_case_1():
    bool_0 = True
    none_type_0 = None
    var_0 = module_0.palindromic_substrings(none_type_0)
    var_1 = module_0.palindromic_substrings_iter(bool_0)


def test_case_2():
    none_type_0 = None
    var_0 = module_0.palindromic_substrings_iter(none_type_0)
    var_1 = module_0.palindromic_substrings(none_type_0)
    var_2 = module_0.palindromic_substrings_iter(none_type_0)
    var_3 = module_0.palindromic_substrings(none_type_0)
    var_4 = module_0.palindromic_substrings(var_3)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "SRr\t)kC"
    var_0 = module_0.palindromic_substrings(str_0)
    none_type_0 = None
    var_1 = module_0.palindromic_substrings_iter(none_type_0)
    int_0 = 2704
    var_2 = module_0.palindromic_substrings_iter(int_0)
    module_0.palindromic_substrings(int_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    none_type_0 = None
    var_0 = module_0.palindromic_substrings_iter(none_type_0)
    module_1.object(*var_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    bool_0 = False
    float_0 = -904.7640188642197
    var_0 = module_0.palindromic_substrings_iter(bool_0)
    var_1 = module_0.palindromic_substrings_iter(float_0)
    module_1.object(*var_1)


@pytest.mark.xfail(strict=True)
def test_case_6():
    bool_0 = False
    var_0 = module_0.palindromic_substrings(bool_0)
    var_1 = module_0.palindromic_substrings_iter(var_0)
    var_2 = module_0.palindromic_substrings_iter(bool_0)
    module_1.object(*var_1)


@pytest.mark.xfail(strict=True)
def test_case_7():
    str_0 = '"@+X'
    var_0 = module_0.palindromic_substrings(str_0)
    none_type_0 = None
    bool_0 = False
    var_1 = module_0.palindromic_substrings_iter(str_0)
    var_2 = module_0.palindromic_substrings_iter(str_0)
    var_3 = module_0.palindromic_substrings(bool_0)
    var_4 = module_0.palindromic_substrings(none_type_0)
    var_5 = module_0.palindromic_substrings(bool_0)
    module_1.object(*var_2)
