# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.stack as module_0


def test_case_0():
    bytes_0 = b"N\xddC'\x8bi0\xbc\x80{~x"
    list_0 = [bytes_0]
    var_0 = module_0.remove_min(list_0)
    var_1 = module_0.remove_min(var_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "`Z8Q4C"
    module_0.remove_min(str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = False
    module_0.remove_min(bool_0)


def test_case_3():
    bytes_0 = b"N\xddC'\x8bi0\xbc\x80{~x"
    list_0 = [bytes_0]
    var_0 = module_0.remove_min(list_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    tuple_0 = ()
    bool_0 = False
    tuple_1 = (bool_0,)
    list_0 = [tuple_0, tuple_1, tuple_0]
    var_0 = module_0.remove_min(list_0)
    bool_1 = True
    module_0.remove_min(bool_1)
